### ISSUE TITLE
Flashing white page in dark mode while redirecting

### ISSUE THREAD

**Issue by exsesx** [kagisearch/Kagi-Search-for-Safari-iOS#4]
On iOS, if I use the extension, everything works fine, but every time I search for something, I get a white page while redirecting and then my search results, which is pretty annoying. I've tried every supported search engine on iOS, and none struggle with this issue.

**Comment by exsesx** [comment]
And there's not much to do here, I guess.

Seems like a browser issue. Chrome flags fix this with force-dark-mode enabled, but it breaks some websites. DarkReader is a much more flexible solution, but limited.

**Comment by vprelovac** [comment]
Our hands are tied by what Safari allows us to do. Peharps try setting dark mode on Google (as we have to redirect from it to Kagi).

Much better solution woud be to use Orion browser instead which has Kagi built in.
https://browser.kagi.com
